// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	channels2 "github.com/roman-mazur/chat-channels-example/pkg/channels"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*ChatApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := channels2.NewStore(db)
	httpHandlerFunc := channels2.HttpHandler(store)
	chatApiServer := &ChatApiServer{
		Port:            port,
		ChannelsHandler: httpHandlerFunc,
	}
	return chatApiServer, nil
}
